TravelApp/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TravelApp.Models;
using TravelApp.Repository.Abstract;

namespace TravelApp.Controllers
{
    public class BlogController : Controller
    {

        private IBlogRepository _blogRepository;

        public BlogController(IBlogRepository blogRepo)
        {
            _blogRepository = blogRepo;
        }

        public IActionResult Index(int? id)
        {
            var query = _blogRepository.GetAll()
                         .Where(i => i.isShared);

            return View(query.OrderByDescending(i => i.BlogId));
        }

        public IActionResult Details(int id)
        {
            return View(_blogRepository.GetByID(id));
        }

        [Authorize(Roles = "Admin")]
        public IActionResult List()
        {
            return View(_blogRepository.GetAll());
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            return View(new Blog());
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Create(Blog entity)
        {
            if (ModelState.IsValid)
            {
                _blogRepository.SaveBlog(entity);
                TempData["message"] = $"{entity.BlogTittle} kayıt edildi.";
                return RedirectToAction("List");
            }

            return View(entity);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View(_blogRepository.GetByID(id));
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(Blog entity, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", file.FileName);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);

                        entity.BlogImage = file.FileName;
                    }
                }

                _blogRepository.SaveBlog(entity);
                TempData["message"] = $"{entity.BlogTittle} kayıt edildi.";
                return RedirectToAction("List");
            }

            return View(entity);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_blogRepository.GetByID(id));
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int BlogId)
        {
            _blogRepository.DeleteBlog(BlogId);
            TempData["message"] = $"{BlogId} numaralı kayıt edildi.";
            return RedirectToAction("List");
        }

    }
}

TravelApp/Controllers/LokantaController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TravelApp.Models;
using TravelApp.Repository.Abstract;

namespace TravelApp.Controllers
{
    public class LokantaController : Controller
    {
        private ILokantaRepository _lokantaRepository;
        private ISehirRepository _sehirRepository;

        public LokantaController(ILokantaRepository lokantaRepo, ISehirRepository sehirRepo)
        {
            _lokantaRepository = lokantaRepo;
            _sehirRepository = sehirRepo;
        }

        public IActionResult Index(int? id)
        {
            var query = _lokantaRepository.GetAll();

            if (id != null)
            {
                query = query
                    .Where(i => i.SehirId == id);
            }

            return View(query.OrderByDescending(i => i.LokantaId));
        }

        [Authorize(Roles = "Admin")]
        public IActionResult List()
        {
            return View(_lokantaRepository.GetAll());
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Sehirs = new SelectList(_sehirRepository.GetAll(), "SehirId", "sehirAd");

            return View(new Lokanta());
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Create(Lokanta entity)
        {
            if (ModelState.IsValid)
            {
                _lokantaRepository.SaveLokanta(entity);
                TempData["message"] = $"{entity.lokantaAd} kayıt edildi.";
                return RedirectToAction("List");
            }

            ViewBag.Categories = new SelectList(_sehirRepository.GetAll(), "SehirId", "sehirAd");
            return View(entity);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Sehirs = new SelectList(_sehirRepository.GetAll(), "SehirId", "sehirAd");

            return View(_lokantaRepository.GetByID(id));
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(Lokanta entity, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", file.FileName);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);

                        entity.lokantaImage = file.FileName;
                    }
                }

                _lokantaRepository.SaveLokanta(entity);
                TempData["message"] = $"{entity.lokantaAd} kayıt edildi.";
                return RedirectToAction("List");
            }

            ViewBag.Sehirs = new SelectList(_sehirRepository.GetAll(), "SehirId", "sehirAd");
            return View(entity);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_lokantaRepository.GetByID(id));
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int LokantaId)
        {
            _lokantaRepository.DeleteLokanta(LokantaId);
            TempData["message"] = $"{LokantaId} numaralı kayıt edildi.";
            return RedirectToAction("List");
        }

    }
}

TravelApp/Controllers/OtelController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TravelApp.Models;
using TravelApp.Repository.Abstract;

namespace TravelApp.Controllers
{
    public class OtelController : Controller
    {
        private IOtelRepository _otelRepository;
        private ISehirRepository _sehirRepository;

        public OtelController(IOtelRepository otelRepo, ISehirRepository sehirRepo)
        {
            _otelRepository = otelRepo;
            _sehirRepository = sehirRepo;
        }

        public IActionResult Index(int? id)
        {
            var query = _otelRepository.GetAll();

            if (id != null)
            {
                query = query
                    .Where(i => i.SehirId == id);
            }

            return View(query.OrderByDescending(i => i.OtelId));
        }

        [Authorize(Roles = "Admin")]
        public IActionResult List()
        {
            return View(_otelRepository.GetAll());
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Sehirs = new SelectList(_sehirRepository.GetAll(), "SehirId", "sehirAd");

            return View(new Otel());
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Create(Otel entity)
        {
            if (ModelState.IsValid)
            {
                _otelRepository.SaveOtel(entity);
                TempData["message"] = $"{entity.otelAd} kayıt edildi.";
                return RedirectToAction("List");
            }

            ViewBag.Categories = new SelectList(_sehirRepository.GetAll(), "SehirId", "sehirAd");
            return View(entity);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Sehirs = new SelectList(_sehirRepository.GetAll(), "SehirId", "sehirAd");

            return View(_otelRepository.GetByID(id));
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(Otel entity, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", file.FileName);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);

                        entity.otelImage = file.FileName;
                    }
                }

                _otelRepository.SaveOtel(entity);
                TempData["message"] = $"{entity.otelAd} kayıt edildi.";
                return RedirectToAction("List");
            }

            ViewBag.Categories = new SelectList(_sehirRepository.GetAll(), "SehirId", "sehirAd");
            return View(entity);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_otelRepository.GetByID(id));
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int OtelId)
        {
            _otelRepository.DeleteOtel(OtelId);
            TempData["message"] = $"{OtelId} numaralı kayıt edildi.";
            return RedirectToAction("List");
        }

    }
}

TravelApp/Controllers/SoruController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TravelApp.Models;
using TravelApp.Repository.Abstract;

namespace TravelApp.Controllers
{
    public class SoruController : Controller
    {
        private ISoruRepository _soruRepository;


        public SoruController(ISoruRepository soruRepo)
        {
            _soruRepository = soruRepo;
        }

        public IActionResult Index(int? id)
        {

            var query = _soruRepository.GetAll();


            return View(query.OrderByDescending(i => i.SoruId));
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {

            return View(new Soru());
        }

        [Authorize]
        [HttpPost]
        public IActionResult Create(Soru entity)
        {
            if (ModelState.IsValid)
            {
                _soruRepository.SaveSoru(entity);
                TempData["message"] = $"{entity.soruTittle} kayıt edildi.";
                return RedirectToAction("Index");
            }
            return View(entity);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View(_soruRepository.GetByID(id));
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Edit(Soru entity)
        {
            if (ModelState.IsValid)
            {
                _soruRepository.SaveSoru(entity);
                TempData["message"] = $"{entity.soruTittle} kayıt edildi";
                return RedirectToAction("Index");
            }

            return View(entity);
        }
    }
}

TravelApp/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/Style.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>_Layout</title>
</head>
<body>

    @if (User.Identity.IsAuthenticated)
    {
        if (User.IsInRole("Admin"))
        {
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">TravelApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="Index" class="nav-link">Ana Sayfa<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Blog
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a asp-controller="Blog" asp-action="Index" class="dropdown-item">Blog Sayfası</a>
                                <a asp-controller="Blog" asp-action="Create" class="dropdown-item">Blog Ekle</a>
                                <a asp-controller="Blog" asp-action="List" class="dropdown-item">Blogları Listele</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Otel
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a asp-controller="Otel" asp-action="Index" class="dropdown-item" asp-route-id="null">Otel Sayfası</a>
                                <a asp-controller="Otel" asp-action="Create" class="dropdown-item">Otel Ekle</a>
                                <a asp-controller="Otel" asp-action="List" class="dropdown-item">Otelleri Listele</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Lokanta
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a asp-controller="Lokanta" asp-action="Index" asp-route-id="null" class="dropdown-item">Lokanta Sayfası</a>
                                <a asp-controller="Lokanta" asp-action="Create" class="dropdown-item">Lokanta Ekle</a>
                                <a asp-controller="Lokanta" asp-action="List" class="dropdown-item">Lokantaları Listele</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Kullanıcı İşlemleri
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a asp-controller="AdminRole" asp-action="Index" class="nav-link">Kullanıcıya Rol Ver / Yeni Rol Ekle </a>
                                <a asp-controller="Admin" asp-action="Index" class="nav-link">Kullanıcıları Listele</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Soru" asp-action="Index" class="nav-link">Sorular<span class="sr-only"></span></a>
                        </li>
                        <li class="navbar-toggler-right" style="margin:9px">
                            <p>
                                @User.Identity.Name
                                <a asp-action="Logout" asp-controller="Account">Çıkış</a>
                            </p>
                        </li>
                    </ul>
                </div>
            </nav>
        }
        else
        {
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">TravelApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="Index" class="nav-link">Ana Sayfa<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Otel" asp-action="Index" asp-route-id="null" class="nav-link">Otel</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Lokanta" asp-action="Index" asp-route-id="null" class="nav-link">Lokanta</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Blog" asp-action="Index" class="nav-link">Blog</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Soru
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a asp-controller="Soru" asp-action="Index" class="nav-link">Sorular</a>
                                <a asp-controller="Soru" asp-action="Create" class="nav-link">Yeni Soru Sor</a>
                            </div>
                        </li>
                        <li class="navbar-toggler-right" style="margin:9px">
                            <p>
                                @User.Identity.Name
                                <a asp-action="Logout" asp-controller="Account">Çıkış</a>
                            </p>
                        </li>
                    </ul>
                </div>
            </nav>
        }
    }
    else
    {
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a asp-controller="Home" asp-action="Index" class="navbar-brand">TravelApp</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Index" class="nav-link">Ana Sayfa<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Otel" asp-action="Index" asp-route-id="null" class="nav-link">Otel</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Lokanta" asp-action="Index" asp-route-id="null" class="nav-link">Lokanta</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Blog" asp-action="Index" class="nav-link">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Soru" asp-action="Index" class="nav-link">Sorular</a>
                    </li>
                    <li class="nav-item dropdown navbar-toggler-right">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Giriş İşlemeleri
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a asp-controller="Account" asp-action="Login" class="nav-link"> Giriş </a>
                            <a asp-controller="Admin" asp-action="Create" class="nav-link">Kayıt Ol</a>
                        </div>
                    </li>

                </ul>
            </div>
        </nav>
    }
    <br />
    @RenderBody()
    @RenderSection("scripts", false)
    <br />
    <br />
    <footer class="card-footer" style="background-color:#bcb7b7">
        <div class="card-group">
            <div class="card">

                <div class="card-block" style="background-color:#bcb7b7">
                    <h6 class="card-title" style="text-align:center">Sayfalar</h6>
                    <hr />
                    <p class="card-text" style="text-align:center">
                        <a asp-controller="Home" asp-action="Index">ANA SAYFA</a>   |   <a asp-controller="Blog" asp-action="Index">BLOG</a> |   <a asp-controller="Otel" asp-action="Index">OTEL</a>  |
                        <a asp-controller="Lokanta" asp-action="Index">LOKANTA</a>
                    </p>
                    <hr />

                </div>
            </div>
            <div class="card">

                <div class="card-block" style="background-color:#bcb7b7">
                    <h6 class="card-title" style="text-align:center">İletişim</h6>
                    <p class="card-text" style="text-align:center"><i class="fa fa-phone" aria-hidden="true"> 0216 321 1415</i></p>
                    <p class="card-text" style="text-align:center"><i class="fa fa-location-arrow" aria-hidden="true"> Teşvikiye Mahallesi Abdi İpekçi Caddesi Numara: 5 Şişli/İstanbul </i></p>
                    <p class="card-text" style="text-align:center"><i class="fa fa-envelope" aria-hidden="true"> info@travelapp.com.tr </i></p>

                </div>
            </div>
            <div class="card">

                <div class="card-block" style="background-color:#bcb7b7">
                    <h6 class="card-title" style="text-align:center">Hakkımızda</h6>
                    <p class="card-text" style="text-align:center; font-style:italic">Travel App bir seyehat öneri sitesidir. Buradan Lokanta, Otel önerileri alabilceğiniz gibi yazılan eğlenceli Bloglarla çok iyi vakit geçirebilirsiniz.</p>

                </div>
            </div>
        </div>
    </footer>


</body>
</html>